# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: fd638f4
_src_path: gh:/EasyScience/EasyProjectTemplate
description: A reflectometry python package built on the EasyScience framework.
max_python: '3.12'
min_python: '3.9'
orgname: EasyScience
packagename: easyreflectometry
prettyname: Easy Reflectometry Library
projectname: EasyReflectometryLib
year: 2024
