[project]
name = "easyreflectometry"
version = "0.1.0"
description = "A reflectometry python package built on the EasyScience framework."
authors = ["EasyScience contributors"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[environments]
default = ["dev", "py313"]
py311-dev = ["dev", "py311"]
py312-dev = ["dev", "py312"]
py313-dev = ["dev", "py313"]
docs = ["docs"]

# Unix/macOS
[target.unix.activation.env]
PYTHONPATH = "src${PYTHONPATH:+:${PYTHONPATH}}" # remove ":" if needed

# Windows
[target.win.activation.env]
PYTHONPATH = "src;%PYTHONPATH%"

# Features for specific Python versions

# Each feature sets a specific Python version for the environment.

[feature.py311.dependencies]
python = '3.11.*'

[feature.py312.dependencies]
python = '3.12.*'

[feature.py313.dependencies]
python = '3.13.*'

[dependencies] # == [feature.default.dependencies]
pip = '*'        # Required to install from PyPI
jupyterlab = '*' # JupyterLab for notebooks


[pypi-dependencies]
easyreflectometry = { version = '*', editable = true }
pixi-kernel = '*'                                               # Pixi Jupyter kernel
uv = '*'                                                        # Python package manager
easyscience = "*"
scipp = "*"
refnx = "*"
refl1d = ">=1.0.0rc0"
orsopy = "*"
bumps = "*"
xhtml2pdf = "*"

[tasks]
install-dev = "pip install -e '.[dev]'"
test = "pytest --cov=src/easyreflectometry tests --cov-branch --cov-report=xml:coverage-unit.xml"
lint = "ruff check ."
lint-fix = "ruff check . --fix"
build = "python -m build"

[feature.dev.dependencies]
coverage = "*"
flake8 = "*"
ipykernel = "*"
jupyter = "*"
jupyterlab = "*"
pooch = "*"
pytest = "*"
pytest-cov = "*"
ruff = "*"
toml = "*"
yapf = "*"

[feature.dev.pypi-dependencies]
build = "*"
codecov = "*"
coveralls = "*"
plopp = "*"

[feature.docs.dependencies]
sphinx = "==8.1.3"
toml = "*"

[feature.docs.pypi-dependencies]
myst-parser = "*"
nbsphinx = "*"
sphinx-autodoc-typehints = "*"
sphinx-book-theme = "*"
sphinx-copybutton = "*"
