# This pipeline 
# - build html documentation 
# - deploy html documentation to gh-pages branch of the same repository

name: Build and Deploy Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Pandoc, EasyReflectometry and dependencies
      run: |
        sudo apt install pandoc
        pip install . '.[dev]'
    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        install_requirements: true
        documentation_path: docs
    - name: Push changes
      uses: ad-m/github-push-action@master
      continue-on-error: true
      with:
        branch: gh-pages