# This pipeline
# - builds developer documentation using pixi
# - pushes documentation to gh-pages branch of the same repository
#
# Deployment is handled by pages-build-deployment bot
#
# For more information see: https://docs.github.com/en/pages/getting-started-with-github-pages

name: Build Documentation and Push to gh-pages Branch (Pixi)

# Controls when the workflow will run
on:
  # Triggers the workflow on tag creation
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.9.0
      with:
        run-install: false
        cache: false
        post-cleanup: false

    - name: Install Pandoc
      run: sudo apt install pandoc

    - name: Install dependencies
      run: |
        pixi install -e docs
        pixi run -e docs install-dev

    - name: Build documentation
      run: pixi run -e docs docs-build

    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        install_requirements: false
        sphinx_version: 8.1.3
        documentation_path: docs/src

    - name: Push changes
      uses: ad-m/github-push-action@master
      continue-on-error: true
      with:
        branch: gh-pages