# This workflow will
# - build distribution package using pixi, pure python wheel
# - publish produced distribution package to PyPI
#
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries


name: Publish Python Package (Pixi)

# Controls when the workflow will run
on:
  # Triggers the workflow on tag creation
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.9.0
      with:
        run-install: false
        cache: false
        post-cleanup: false

    - name: Install dependencies and build
      run: |
        python -m pip install -e '.[dev]'
        python -m build

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      #with:
      #  password: ${{ secrets.PYPI_PASSWORD }}